import { Metadata } from "next"


import Header from "../components/header"
import '../styles/global.css'
import 'bootstrap/dist/css/bootstrap.min.css'

export const metadata: Metadata = {
  title: {
    template: "%s | OpenWeather",
    default: "Devchun"
  },
  description: "OpenWeather Api generated by Devchun"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <section className="container">
          <Header />
          <section style={{ height: "600px" }}>
            {children}
          </section>
        </section>

      </body>
    </html>
  )
}
